version: "2"
services:
  mysql:
   
    image: mysql
    environment:     
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: srinitrainingdb
  productservice:   
    build: ./productservice
    environment:
      spring.profiles.active: mysql
    ports:
     - 8080:8080
     